---
version: "2.1"

services:
  archivematica-tests:
    build:
      context: "../"
      dockerfile: "hack/Dockerfile"
      args:
        TARGET: "archivematica-tests"
    volumes:
      - "../:/src"
