---
name: "Acceptance Test"
on:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "stable/**"
      - "dev/amauat-workflow"
jobs:
  test:
    name: "Test ${{ matrix.tag }}"
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "mo-aip-reingest"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start services"
        run: |
          docker-compose up -d
        working-directory: ./hack
      - name: "Wait for MySQL to start"
        run: |
          sleep 20
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Wait for services to restart"
        run: |
          sleep 20
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS=${{ matrix.tag }}
      - name: "Display dashboard logs"
        run: |
          docker-compose logs -t archivematica-dashboard
        working-directory: ./hack
      - name: "Display MCPServer logs"
        run: |
          docker-compose logs -t archivematica-mcp-server
        working-directory: ./hack
      - name: "Display MCPClient logs"
        run: |
          docker-compose logs -t archivematica-mcp-client
        working-directory: ./hack
      - name: "Display Storage Service logs"
        run: |
          docker-compose logs -t archivematica-storage-service
        working-directory: ./hack
