---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "dev/issue-1140-test-settings"
jobs:
  test:
    name: "Test ${{ matrix.rule }}"
    runs-on: "ubuntu-18.04"
    continue-on-error: true
    strategy:
      matrix:
        rule:
          - mcp-server
          - mcp-client
          - dashboard
          - archivematica-common
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          ref: "dev/issue-1140-test-settings"
          submodules: true
      - name: "Set up pip cache"
        uses: "actions/cache@v2"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Set up tox cache"
        uses: "actions/cache@v2"
        with:
          path: ./.tox
          key: "${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}"
          restore-keys: |
            ${{ runner.os }}-tox-
      - name: "Pull percona image"
        working-directory: hack
        run: |
          docker-compose pull mysql
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v1"
        id: buildx
        with:
          install: true
      - name: "Cache Docker layers"
        uses: "actions/cache@v2"
        with:
          path: /tmp/.docker-cache-old
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: "Build"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./hack/Dockerfile
          target: archivematica-tests
          tags: archivematica-tests:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "List docker images"
        run: |
          docker image ls --no-trunc
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Run make rule"
        run: |
          make -C hack/ test-${{ matrix.rule }}
      - name: "Move cache"
        run: |
          rm -rf /tmp/.docker-cache-old
          mv /tmp/.docker-cache-new /tmp/.docker-cache-old
