---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "stable/**"
      - "dev/issue-1140-test-settings"
jobs:
  test:
    name: "Test ${{ matrix.rule }}"
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        rule:
          - mcp-server
          - mcp-client
          - dashboard
          - archivematica-common
          - storage-service
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          ref: "dev/issue-1140-test-settings"
          submodules: true
      - name: "Set up pip cache"
        uses: "actions/cache@v2"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Set up tox cache"
        uses: "actions/cache@v2"
        with:
          path: ./.tox
          key: "${{ runner.os }}-tox-${{ matrix.rule }}-${{ hashFiles('**/tox.ini') }}"
          restore-keys: |
            ${{ runner.os }}-tox-${{ matrix.rule }}-
            ${{ runner.os }}-tox-
      - name: "Set up MySQL cache"
        uses: "actions/cache@v2"
        id: mysql_cache
        with:
          path: /tmp/.mysql-data
          key: "${{ runner.os }}-mysql-${{ matrix.rule }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-mysql-${{ matrix.rule }}-
            ${{ runner.os }}-mysql-
      - name: "Create MySQL data directory"
        if: steps.mysql_cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: |
          mkdir /tmp/.mysql-data
      - name: "Set permissions on MySQL data directory"
        run: |
          chmod 777 /tmp/.mysql-data
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v1"
        id: buildx
        with:
          install: true
      - name: "Set up docker cache"
        uses: "actions/cache@v2"
        with:
          path: /tmp/.docker-cache-old
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: "Build archivematica-tests image"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./hack/Dockerfile
          target: archivematica-tests
          tags: archivematica-tests:latest
          push: false
          load: true
          cache-from: type=local,src=/tmp/.docker-cache-old
          cache-to: type=local,dest=/tmp/.docker-cache-new,mode=max
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Run make rule"
        run: |
          make -C hack/ test-${{ matrix.rule }}
        env:
          MYSQL_VOLUME: "/tmp/.mysql-data"
      - name: "Set newest docker cache"
        run: |
          rm -rf /tmp/.docker-cache-old
          mv /tmp/.docker-cache-new /tmp/.docker-cache-old
      - name: "Set permissions on MySQL data directory"
        run: |
          sudo chmod -R 777 /tmp/.mysql-data
